"""Public reusable component value objects for ASTROX SDK workflows.

ASTROX uses the word ``Orientation`` at two different levels. Entity
``Orientation`` fields are coordinate axes definitions from the ``CrdnAxes``
schema family: VVLH, LVLH, VNC, Fixed, FixedAtEpoch, Composite, and CZML-backed
axes. Sensor pointing and fixed axes then contain smaller Az/El, quaternion, or
Euler-angle orientation fragments. The SDK names those two levels separately:
public constructors and dataclasses use ``Axes`` for entity-level attitude
frames and ``Rotation`` for the inner Az/El, quaternion, or Euler fragments.
"""

from __future__ import annotations

from ._axes import (
    AlignedAndConstrainedAxes,
    CompositeAxes,
    CzmlAxes,
    EntityAxes,
    FixedAtEpochAxes,
    FixedAxes,
    LvlhAxes,
    VncAxes,
    VvlhAxes,
    _axes_reference_name,
    _axes_to_wire,
    aligned_and_constrained_axes,
    composite_axes,
    czml_axes,
    fixed_at_epoch_axes,
    fixed_axes,
    lvlh_axes,
    vnc_axes,
    vvlh_axes,
)
from ._constraints import (
    AzElMaskConstraint,
    Constraint,
    ElevationConstraint,
    RangeConstraint,
    _constraint_to_wire,
    az_el_mask_constraint,
    elevation_constraint,
    range_constraint,
)
from ._objects import Entity, EntityGroup, entity, entity_group
from ._positions import (
    BallisticPosition,
    CentralBodyPosition,
    CzmlPosition,
    CzmlPositionSTM,
    CzmlPositions,
    EntityPosition,
    HpopPosition,
    J2Position,
    Sgp4Position,
    SimpleAscentPosition,
    SitePosition,
    TwoBodyPosition,
    _position_to_wire,
    _site_position_to_wire,
    ballistic_position,
    central_body_position,
    czml_position,
    czml_positions,
    hpop_position,
    j2_position,
    sgp4_position,
    simple_ascent_position,
    site_position,
    two_body_position,
)
from ._rotations import (
    AzElRotation,
    EulerRotation,
    QuaternionRotation,
    Rotation,
    _rotation_to_wire,
    az_el_rotation,
    euler_rotation,
    quaternion_rotation,
)
from ._sensors import (
    ConicSensor,
    EntitySensor,
    FixedSensorPointing,
    RectangularSensor,
    SensorPointing,
    _sensor_pointing_to_wire,
    _sensor_to_wire,
    conic_sensor,
    fixed_sensor_pointing,
    rectangular_sensor,
)
from ._vgt import (
    RaDecDirection,
    VgtAngle,
    VgtDirection,
    VgtFixedVector,
    VgtPlane,
    VgtPoint,
    VgtProvider,
    VgtSystem,
    VgtVector,
    XyzDirection,
    _direction_to_wire,
    _vector_reference_name,
    _vgt_to_wire,
    ra_dec_direction,
    vgt,
    vgt_angle,
    vgt_fixed_vector,
    vgt_plane,
    vgt_point,
    vgt_system,
    xyz_direction,
)

__all__ = [
    "AlignedAndConstrainedAxes",
    "AzElRotation",
    "BallisticPosition",
    "CentralBodyPosition",
    "AzElMaskConstraint",
    "ConicSensor",
    "CompositeAxes",
    "Constraint",
    "CzmlPosition",
    "CzmlPositionSTM",
    "CzmlPositions",
    "CzmlAxes",
    "ElevationConstraint",
    "Entity",
    "EntityAxes",
    "EntityGroup",
    "EntityPosition",
    "EntitySensor",
    "EulerRotation",
    "FixedAtEpochAxes",
    "FixedAxes",
    "FixedSensorPointing",
    "HpopPosition",
    "J2Position",
    "LvlhAxes",
    "QuaternionRotation",
    "RangeConstraint",
    "RectangularSensor",
    "Rotation",
    "RaDecDirection",
    "SensorPointing",
    "Sgp4Position",
    "SitePosition",
    "SimpleAscentPosition",
    "TwoBodyPosition",
    "VgtAngle",
    "VgtDirection",
    "VgtFixedVector",
    "VgtPlane",
    "VgtPoint",
    "VgtProvider",
    "VgtSystem",
    "VgtVector",
    "VncAxes",
    "VvlhAxes",
    "XyzDirection",
    "aligned_and_constrained_axes",
    "az_el_rotation",
    "az_el_mask_constraint",
    "ballistic_position",
    "central_body_position",
    "conic_sensor",
    "composite_axes",
    "czml_position",
    "czml_positions",
    "czml_axes",
    "entity",
    "entity_group",
    "euler_rotation",
    "elevation_constraint",
    "fixed_axes",
    "fixed_at_epoch_axes",
    "fixed_sensor_pointing",
    "hpop_position",
    "j2_position",
    "lvlh_axes",
    "quaternion_rotation",
    "range_constraint",
    "ra_dec_direction",
    "rectangular_sensor",
    "vgt",
    "vgt_angle",
    "vgt_fixed_vector",
    "vgt_plane",
    "vgt_point",
    "vgt_system",
    "vnc_axes",
    "vvlh_axes",
    "xyz_direction",
    "sgp4_position",
    "site_position",
    "simple_ascent_position",
    "two_body_position",
]
