#!/usr/bin/env python3
"""Generate the OpenAPI fixture coverage status document."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    from scripts.openapi_drift.discovery_report import (
        axis_key,
        discovery_fixture_report,
        value_key,
    )
    from scripts.openapi_drift.discover import discover, load_spec
    from scripts.openapi_drift.verify import iter_fixture_paths, load_fixture
except ModuleNotFoundError:  # pragma: no cover - direct script execution fallback
    from discovery_report import axis_key, discovery_fixture_report, value_key
    from discover import discover, load_spec
    from verify import iter_fixture_paths, load_fixture


DEFAULT_OPENAPI = Path("openapi/astrox.openapi.yaml")
DEFAULT_FIXTURE_DIR = Path("openapi/fixtures")
DEFAULT_OUTPUT = Path("openapi/fixtures/STATUS.md")


def endpoint_group(endpoint: str) -> str:
    head = endpoint.strip("/").split("/", 1)[0]
    return head or "Other"


def state_label(state: str) -> str:
    if state == "verified":
        return "x"
    if state == "blocked":
        return "!"
    if state == "partial":
        return "~"
    return " "


def branch_state(branch: dict[str, Any]) -> str:
    state = branch.get("state")
    return state if isinstance(state, str) else "unknown"


def is_nominal_branch(branch_id: str) -> bool:
    return branch_id == "nominal" or branch_id.startswith("nominal_")


def load_fixtures(fixture_dir: Path) -> list[tuple[Path, dict[str, Any]]]:
    return [(path, load_fixture(path)) for path in iter_fixture_paths(fixture_dir)]


def fixture_index(fixtures: list[tuple[Path, dict[str, Any]]]) -> dict[str, list[tuple[Path, dict[str, Any]]]]:
    by_endpoint: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
    for path, fixture in fixtures:
        by_endpoint[fixture["endpoint"]].append((path, fixture))
    return dict(by_endpoint)


def branch_counts(fixtures: list[tuple[Path, dict[str, Any]]]) -> dict[str, int]:
    counts = {
        "verified": 0,
        "blocked": 0,
        "nominal_verified": 0,
        "nominal_blocked": 0,
        "non_nominal_verified": 0,
        "non_nominal_blocked": 0,
    }
    for _, fixture in fixtures:
        for branch_id, branch in fixture["branches"].items():
            state = branch_state(branch)
            if state in {"verified", "blocked"}:
                counts[state] += 1
            if is_nominal_branch(branch_id) and state == "verified":
                counts["nominal_verified"] += 1
            elif is_nominal_branch(branch_id) and state == "blocked":
                counts["nominal_blocked"] += 1
            elif not is_nominal_branch(branch_id) and state == "verified":
                counts["non_nominal_verified"] += 1
            elif not is_nominal_branch(branch_id) and state == "blocked":
                counts["non_nominal_blocked"] += 1
    return counts


def nominal_state_for_endpoint(fixtures: list[tuple[Path, dict[str, Any]]] | None) -> str:
    if not fixtures:
        return "uncovered"
    for _, fixture in fixtures:
        for branch_id, branch in fixture["branches"].items():
            if not is_nominal_branch(branch_id) or not isinstance(branch, dict):
                continue
            state = branch_state(branch)
            if state in {"verified", "blocked"}:
                return state
    return "partial"


def markdown_lines(*, openapi: Path, fixture_dir: Path) -> list[str]:
    endpoints = discover(load_spec(openapi))
    fixtures = load_fixtures(fixture_dir)
    by_endpoint = fixture_index(fixtures)
    counts = branch_counts(fixtures)
    discovery_report = discovery_fixture_report(openapi=openapi, fixture_dir=fixture_dir)
    axis_reports = {
        (axis["endpoint"], axis["axis_key"]): axis
        for axis in discovery_report["axis_reports"]
    }
    discovered_endpoints = {endpoint["endpoint"] for endpoint in endpoints}
    endpoints_without_nominal_evidence = [
        endpoint["endpoint"]
        for endpoint in endpoints
        if nominal_state_for_endpoint(by_endpoint.get(endpoint["endpoint"])) not in {"verified", "blocked"}
    ]

    lines = [
        "# OpenAPI Fixture Status",
        "",
        "<!-- Generated by scripts/openapi_drift/generate_status.py; do not edit by hand. -->",
        "",
        "This file is a deterministic inventory of checked-in ASTROX wire-contract fixtures.",
        "Fixture YAML is the machine source of branch state; OpenAPI discovery is only",
        "used to list endpoint and branch-axis candidates that still need fixture evidence.",
        "",
        f"Source spec: `{openapi}`",
        f"Fixture directory: `{fixture_dir}`",
        "",
        "## Summary",
        "",
        f"- discovered OpenAPI endpoints: {len(endpoints)}",
        f"- fixture endpoint records: {len(fixtures)}",
        f"- verified fixture branches: {counts['verified']}",
        f"- blocked fixture branches: {counts['blocked']}",
        f"- verified nominal endpoint fixtures: {counts['nominal_verified']}",
        f"- blocked nominal endpoint fixtures: {counts['nominal_blocked']}",
        f"- verified non-nominal fixture branches: {counts['non_nominal_verified']}",
        f"- blocked non-nominal fixture branches: {counts['non_nominal_blocked']}",
        f"- discovered endpoints without verified/blocked nominal fixture evidence: {len(endpoints_without_nominal_evidence)}",
        f"- discovered branch axes: {discovery_report['axis_count']}",
        f"- discovered branch axis values: {discovery_report['axis_value_count']}",
        f"- covered discovered branch axis values: {discovery_report['covered_axis_value_count']}",
        f"- uncovered discovered branch axis values: {discovery_report['uncovered_axis_value_count']}",
        "",
        "Legend:",
        "",
        "- `[x]` verified by a checked-in fixture branch",
        "- `[!]` blocked by checked-in fixture evidence",
        "- `[~]` partially covered by checked-in fixture evidence",
        "- `[ ]` discovered from OpenAPI, but no checked-in fixture branch records it",
        "",
        "## Nominal Endpoint Inventory",
        "",
    ]

    endpoints_by_group: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for endpoint in endpoints:
        endpoints_by_group[endpoint_group(endpoint["endpoint"])].append(endpoint)

    for group in sorted(endpoints_by_group, key=str.lower):
        lines.extend([f"### {group}", ""])
        for endpoint in endpoints_by_group[group]:
            endpoint_name = endpoint["endpoint"]
            state = nominal_state_for_endpoint(by_endpoint.get(endpoint_name))
            if state == "verified":
                lines.append(f"- [x] `{endpoint_name}` nominal")
            elif state == "blocked":
                lines.append(f"- [!] `{endpoint_name}` nominal")
            elif state == "partial":
                lines.append(f"- [~] `{endpoint_name}` nominal")
            else:
                lines.append(f"- [ ] `{endpoint_name}` nominal")
        lines.append("")

    fixture_only = sorted(set(by_endpoint) - discovered_endpoints)
    if fixture_only:
        lines.extend(["## Fixture-Only Endpoint Records", ""])
        for endpoint in fixture_only:
            for path, _ in by_endpoint[endpoint]:
                lines.append(f"- `{endpoint}` from `{path}`")
        lines.append("")

    lines.extend(
        [
            "## Fixture Branch Inventory",
            "",
            "This section lists checked-in fixture branches exactly as recorded in YAML.",
            "Non-nominal branch names are evidence records, not globally reusable branch",
            "coverage claims.",
            "",
        ]
    )
    for endpoint in sorted(by_endpoint, key=str.lower):
        lines.extend([f"### `{endpoint}`", ""])
        for path, fixture in sorted(by_endpoint[endpoint], key=lambda item: str(item[0])):
            lines.append(f"Fixture: `{path}`")
            for branch_id, branch in fixture["branches"].items():
                state = branch_state(branch)
                label = state_label(state)
                lines.append(f"- [{label}] `{branch_id}` ({state})")
            lines.append("")

    lines.extend(
        [
            "## Discovered Branch Axis Candidates",
            "",
            "The axis/value rows below come from the checked-in OpenAPI document and",
            "are matched against checked-in branch request payloads for the same endpoint.",
            "Coverage here means an exact candidate value appears in fixture YAML; it",
            "does not imply cross-product or semantic coverage.",
            "",
        ]
    )
    for endpoint in endpoints:
        axes = endpoint["branch_axes"]
        if not axes:
            continue
        lines.extend([f"### `{endpoint['endpoint']}`", ""])
        for axis in axes:
            axis_report = axis_reports.get((endpoint["endpoint"], axis_key(axis)), {})
            axis_name = axis["path"]
            kind = axis["kind"]
            property_name = axis.get("property")
            suffix = f", property `{property_name}`" if property_name else ""
            axis_label = state_label(axis_report.get("state", "uncovered"))
            lines.append(f"- [{axis_label}] `{axis_name}` ({kind}{suffix})")
            values = axis.get("values")
            if isinstance(values, list):
                value_reports = {
                    value_key(value_report["value"]): value_report
                    for value_report in axis_report.get("values", [])
                }
                for value in values:
                    value_report = value_reports.get(value_key(value), {})
                    value_label = state_label(value_report.get("state", "uncovered"))
                    lines.append(f"  - [{value_label}] `{value}`")
        lines.append("")

    return lines


def generate_status_text(*, openapi: Path = DEFAULT_OPENAPI, fixture_dir: Path = DEFAULT_FIXTURE_DIR) -> str:
    return "\n".join(markdown_lines(openapi=openapi, fixture_dir=fixture_dir)).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--openapi", type=Path, default=DEFAULT_OPENAPI)
    parser.add_argument("--fixture-dir", type=Path, default=DEFAULT_FIXTURE_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if output would change")
    args = parser.parse_args()

    text = generate_status_text(openapi=args.openapi, fixture_dir=args.fixture_dir)
    current = args.output.read_text(encoding="utf-8") if args.output.exists() else None
    if current != text:
        if args.check:
            print(f"{args.output} is not up to date")
            return 1
        args.output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
